name: Issue Report
description: Something is broken
title: "[Issue]: "
labels: []

body:
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Tell us what happened in a very clear and simple way
      value: Please fill this form with as much information as possible
  - type: textarea
    id: platform
    attributes:
      label: Version Platform Description
      description: Describe your platform (program version, OS, browser)
      value: 
  - type: markdown
    attributes:
      value: |
        Any issues without version information will be closed  
        Look at console log and copy the version string from there  
        For example: `Version: f256fb8b Fri Apr 14 17:41:30 2023 -0400`  

        Additionally provide any relevant platorm information (OS, browser, versions)  
  - type: markdown
    attributes:
      value: |
        If issue is setup, installation or startup related, please check `setup.log` before reporting  
        And when posting console logs, please use code blocks ( \`\`\` ) to format them insead of uploading screenshots  
  - type: markdown
    attributes:
      value: |
        Verify that issue persists after restarting server from command line  
        Restarting from UI or reloading browser is insufficient to create reproducible environment
  - type: markdown
    attributes:
      value: |
        If you have additional extensions installed, try to reproduce the issue with user extensions disabled  
        And if the issue is with compatibility with specific extension, mark it as such when creating the issue  
  - type: markdown
    attributes:
      value: |
        If possible update to latest version before reporting the issue as older versions cannot be properly supported  
        And search existing **issues** and **discussions** before creating a new one  
